"""v0.3.0 AI-orchestration foundation (P1).

Package layout:

* :mod:`.state` — the ``WorkflowState`` skeleton the controller reads/writes.
* :mod:`.tools` — the deterministic tool registry, the OpenAI tool schemas, and
  the binder for the existing judgment tools.

P2 adds the ``FlowAgent`` controller that plans and calls these tools; P3 adds
the non-blocking sidebar interaction.  See ``docs/0.3.0-设计.md``.
"""

from .state import (
    Budget,
    DocInfo,
    Goal,
    Op,
    PageState,
    PageTriage,
    PHASE_COMPLETED,
    PHASE_DONE,
    PHASE_IDLE,
    PHASE_PREPROCESS,
    PHASE_REVIEW,
    PHASE_SPECIAL_PAGES,
    PHASE_TRANSLATE_NORMAL,
    STATUS_DONE,
    STATUS_IN_PROGRESS,
    STATUS_NEEDS_USER,
    STATUS_PENDING,
    WorkflowState,
)
from .tools import (
    AGENT_TOOLS,
    ToolDef,
    agent_openai_tools,
    by_name,
)
from .flow import (
    AgentResult,
    Decision,
    DocumentSession,
    FlowAgent,
    audit_page,
    make_llm_decide,
    make_llm_interpret,
    make_page_executors,
    make_source_tools,
    run_agent_run,
    run_page_visual,
)
from .flow_steps import (
    STANDARD_FLOWS,
    AgentStep,
    Flow,
    FlowCancelled,
    FlowRunState,
    FlowStep,
    ForEachPage,
    IfStep,
    LoopStep,
    STEP_KINDS,
    ToolStep,
    UserStep,
    interpret_decision,
    run_flow,
)
from .user_flows import (
    DETERMINISTIC_TOOLS,
    USER_FLOW_SPECS,
    FlowSpec,
    build_flow,
    compile_from_user,
    flow_tool_names,
    get_user_flow,
    load_user_flow_specs,
    save_flow_spec,
    validate_flow_tools,
)

__all__ = [
    "AGENT_TOOLS",
    "AgentResult",
    "AgentStep",
    "Budget",
    "DETERMINISTIC_TOOLS",
    "Decision",
    "DocInfo",
    "DocumentSession",
    "Flow",
    "FlowAgent",
    "FlowCancelled",
    "FlowRunState",
    "FlowSpec",
    "FlowStep",
    "ForEachPage",
    "Goal",
    "IfStep",
    "LoopStep",
    "Op",
    "PageState",
    "PageTriage",
    "PHASE_COMPLETED",
    "PHASE_DONE",
    "PHASE_IDLE",
    "PHASE_PREPROCESS",
    "PHASE_REVIEW",
    "PHASE_SPECIAL_PAGES",
    "PHASE_TRANSLATE_NORMAL",
    "STANDARD_FLOWS",
    "STATUS_DONE",
    "STATUS_IN_PROGRESS",
    "STATUS_NEEDS_USER",
    "STEP_KINDS",
    "ToolDef",
    "ToolStep",
    "USER_FLOW_SPECS",
    "UserStep",
    "WorkflowState",
    "agent_openai_tools",
    "audit_page",
    "build_flow",
    "by_name",
    "compile_from_user",
    "flow_tool_names",
    "get_user_flow",
    "interpret_decision",
    "load_user_flow_specs",
    "make_llm_decide",
    "make_llm_interpret",
    "make_page_executors",
    "make_source_tools",
    "run_agent_run",
    "run_flow",
    "run_page_visual",
    "save_flow_spec",
    "validate_flow_tools",
]
